version: "3.5"

services:
  store:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    volumes:
      - ./.docker/es/data:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  queue:
    image: rabbitmq:3.8.7-management
    container_name: rabbitmq
    hostname: rabbit
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret-cookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "Admin123"
    ports:
      - 5672:5672
      - 15672:15672

  api:
    container_name: api
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: debug
    volumes:
      - ./src/api:/app
    env_file: ./src/api/development.env
    ports:
      - 7000:7000
      - 5678:5678
    command: tail -f /dev/null
    depends_on:
      store:
        condition: service_started
      queue:
        condition: service_started

  indexer:
    container_name: indexer
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: debug
    env_file: ./src/api/development.env
    command: tail -f /dev/null
    depends_on:
      store:
        condition: service_started
      queue:
        condition: service_started

  reporter:
    container_name: reporter
    build:
      context: ./src/api
      dockerfile: Dockerfile
      target: debug
    env_file: ./src/api/development.env
    command: tail -f /dev/null
    depends_on:
      store:
        condition: service_started
      queue:
        condition: service_started
