version: "3.5"

services:
  search_api:
    container_name: search_api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file: .env.local
    ports:
      - 7000:7000
    command: tail -f /dev/null

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./.docker/mongo/data:/data/db
    restart: always
    ports:
      - 27017:27017

  elasticsearch:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    volumes:
      - ./.docker/es/data:/usr/share/elasticsearch/data
    ports:
      - "9300:9300"
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
