queue : 
  label : "Queue"
  type : "rabbitmq"
  parameters: 
    host_name : "rabbitmq"
    queues:
      - name : "count-queue"
      - name : "count-report-queue"

operators : 
  label : "Operators"
  parameters :
    - name : "md5 hash"
      type : "md5_hash"
      parameters: {}
