store:
  label: "Data Store"
  type: "es_vec"
  parameters:
    host_name: "es"
    image_index_name: "image"
    text_index_name: "text"
    video_index_name: "video"
    audio_index_name: "audio"

amazon_queue:
  label: "Amazon Queue"
  type: "amazonmq"
  parameters:
    host_name: "amazonmq"
    queues:
      - name: "media-index-queue"
      - name: "report-queue"

operators:
  label: "Operators"
  parameters:
    - name: "Video Vector Representation"
      type: "vid_vec_rep_resnet"
      parameters: { index_name: "video" }
    - name: "Audio Vector Representation"
      type: "audio_vec_embedding"
      parameters: { index_name: "audio" }

# postgresql:
#   label: "PostgreSQL"
#   type: "postgresql"
#   parameters:
#     table_names:
#       - name: "user_message_inbox_perceptually_similar"