store :
  label : "Data Store"
  type : "es_vec"
  parameters:
    - host_name : "es"
    - image_index_name : "image"
    - text_index_name : "text"
    - video_index_name : "video"

queue : 
  label : "Rabbit MQ Queue"

logger : 
  label : "Logger"
  parameters:
    level : "info"

server : 
  label : "Server"
  parameters :
    port : 3000
    type : "https"
  
index :
  label : "Media Indexer"
  parameters:
    supported_media :
      - text
      - image
      - video 
    operators : 
    - name : "image indexer"
      media_type : "image"
      type : "composite_image_text_indexer"
      parameters:
        dimension : 256
    - name : "text indexer"
      media_type : "text"
      type : "text_fulltext_rep"
      parameters:
        dimension : 256
    - name : "video indexer"
      media_type : "video"
      type : "vid_vec_rep_resnet"
      parameters:
        max_length : "2min"
        max_size : "5mb"
        max_resolution: 
          width : 1024
          height : 1024

search : 
  label : "Search"


