name: Publish Video Operator to Dockerhub

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push amd64
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: benchmark/vidvec/Dockerfile.vid_vec_rep_resnet
          platforms: linux/amd64
          push: true
          tags: tattletech/feluda-operator-vidvec:benchmark-amd64-latest-test

      - name: Build and push arm64
        uses: docker/build-push-action@v5
        with:
          context: ./src/
          file: benchmark/vidvec/Dockerfile.vid_vec_rep_resnet.graviton
          platforms: linux/arm64
          push: true
          tags: tattletech/feluda-operator-vidvec:benchmark-arm64-latest-test
