name: Publish Video Worker to Dockerhub for Staging

on: workflow_dispatch

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: development
      - name: "Setup Node version"
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: elgohr/Publish-Docker-Github-Action@main
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/feluda-operator-vidvec
          workdir: src/worker/vidvec/
          dockerfile: Dockerfile.test_video_worker
          tags: latest-amd64
          platforms: linux/amd64