name: Publish Video Operator to Dockerhub

on: workflow_dispatch

jobs:
  api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: "Setup Node version"
        uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: elgohr/Publish-Docker-Github-Action@main
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/feluda-operator-vidvec
          workdir: src/
          dockerfile: benchmark/vidvec/Dockerfile.vid_vec_rep_resnet
          tags: benchmark-amd64-latest
          platforms: linux/amd64
      - uses: elgohr/Publish-Docker-Github-Action@main
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/feluda-operator-vidvec
          workdir: src/
          dockerfile: benchmark/vidvec/Dockerfile.vid_vec_rep_resnet_graviton
          tags: benchmark-arm64-latest
          platforms: linux/arm64

      # - name: deploy to cluster
      #   uses: steebchen/kubectl@v2.0.0
      #   with: # defaults to latest kubectl binary version
      #     config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #     command: set image --record deployment/feluda-server feluda-server=tattletech/feluda-server:${{ steps.vars.outputs.sha_short }}
      # - name: verify deployment
      #   uses: steebchen/kubectl@v2.0.0
      #   with:
      #     config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
      #     version: v1.21.0 # specify kubectl binary version explicitly
      #     command: rollout status deployment/feluda-server
