name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      api: ${{ steps.filter.outputs.api}}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - uses: dorny/paths-filter@v2.2.0
        id: filter
        with:
          filters: |
            api:
                - 'src/api/**/*'

  api:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.api == 'true' }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: development
      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "setting variables"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
          pwd
          ls

      - uses: elgohr/Publish-Docker-Github-Action@master
        with:
          username: tattletech
          password: ${{ secrets.DOCKER_PASSWORD }}
          name: tattletech/feluda-server
          tags: ${{ steps.vars.outputs.sha_short }}
          workdir: src/api/

      - uses: actions/checkout@master
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
          command: set image --record deployment/feluda-server feluda-server=feluda-api:${{ github.sha }}
      - name: verify deployment
        uses: steebchen/kubectl@v2.0.0
        with:
          config: ${{ secrets.PROD_KUBE_CONFIG_DATA }}
          version: v1.21.0 # specify kubectl binary version explicitly
          command: rollout status deployment/feluda-api

  notify:
    runs-on: ubuntu-latest
    needs: [api]
    if: ${{ always() }}
    steps:
      - name: Notify on Slack
        uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: "Deploy Feluda Production"
          SLACK_TITLE: "Deploy Feluda Production  workflow complete"
          SLACK_COLOR: "#020637"
          SLACK_ICON: https://tattle-media.s3.amazonaws.com/monogram-dark.svg

